feat: implement egg guardian
eggjs/egg-guardian pull request #1
Opened 2018-12-10 13:26 UTC by killagu

2018-12-11 05:26 UTC, popomore requested changes

2018-12-11 05:26 UTC, popomore commented on config/config.default.js
> +          // responseContent: '',
默认值可以不用注释

2018-12-11 05:26 UTC, popomore commented on lib/core/guardian.js
> +  constructor(options) {
这里有参数？

2018-12-11 05:26 UTC, popomore commented on lib/core/guardian.js
> +  guardMw() {
这里用全称吧

2018-12-11 05:26 UTC, popomore commented on lib/core/guardian.js
> +  insertRuleAfter(rule, name) {
可以抽一个 rulemanager 对象

2018-12-11 05:26 UTC, popomore commented on lib/core/guardian.js
> +  insertRuleAfter(rule, name) {
可以加个 delete

2018-12-11 05:26 UTC, popomore commented on lib/interrupters/redirect_interrupter.js
> +    ctx.unsafeRedirect(this.redirectUrl);
默认还是用 redirect

2018-12-11 05:26 UTC, popomore commented on lib/validators/qps_validator.js
> +class QpsValidator extends Validator {
这个 @leoner 也看看

2018-12-11 05:26 UTC, popomore commented on app.js
> +      for (const rule of rules) {
这里直接就用串行？不要 Promise.all 了

2018-12-11 05:26 UTC, popomore commented on app.js
> +    return path.join(this.app.config.baseDir, 'app/rule');
rule 这目录太通用了，要不就换成 app/guardian

2018-12-11 05:26 UTC, popomore commented on app/middleware/guardian.js
> +    mw(ctx, next);
这里要 return 下，加个用例

2018-12-11 05:26 UTC, popomore commented on lib/core/guardian.js
> +  addRule(rule) {
改成 pushRule popRule? 或者改成 insertRule

2018-12-11 15:26 UTC, killagu commented on app.js
> +      for (const rule of rules) {
这里实例化 rule 用 Promise.all 会快一点。顺序应该是无所谓的。

2018-12-11 15:26 UTC, killagu commented on app.js
> +    return path.join(this.app.config.baseDir, 'app/rule');
可以的。

2018-12-12 07:03 UTC, leoner commented on lib/core/rule.js
> +    assert(options.validator);
有没有必要, 这里严格校验, 就是 validator 和 interrupter 必须是 Validator 和 Interrupter 的子类

2018-12-12 07:03 UTC, leoner commented on test/core/guardian.test.js
> +          guardian.insertRuleBefore({ name: 'rule1' }, 'rule2');
就是我们实际中, 有碰到要插入到指定规则之前和之后的需求?

2018-12-12 07:36 UTC, killagu commented on lib/core/rule.js
> +    assert(options.validator);
没这个必要，只要是实现接口就好了。

2018-12-12 07:38 UTC, killagu commented on test/core/guardian.test.js
> +          guardian.insertRuleBefore({ name: 'rule1' }, 'rule2');
这个暂时还没有，现在实际的其实就两个，一个限流一个安全。没有顺序上的需求。

这里的实现接近中间件的实现，所以先一并实现了。

2018-12-14 10:15 UTC, popomore commented on README.md
> +npm i @eggjs/egg-guardian
这个要改一下

2018-12-14 10:15 UTC, popomore commented on README.md
> +module.exports = class CustomValidator extends app.GuardianValidator {
这个看起来写的不对

2018-12-14 10:15 UTC, popomore commented on README.md
> +  sufValidate() {
这里要先说明一下两个类的 API 分别是什么

2018-12-14 10:15 UTC, popomore commented on README.md
> +    super(options);
这里有什么

2018-12-14 10:15 UTC, popomore commented on README.md
> +        interrupter: 'CustomInterrupter',
如果这样的话，是不是配置路径更好理解，怎么想得到这个在哪里定义的。

2018-12-14 10:15 UTC, popomore commented on README.md
> +      thresholdMap: {
这个配置是不是应该针对每个 rule，不然不知道 rule 都有哪些配置。

2018-12-14 10:15 UTC, popomore commented on app/guardian/interrupter/log_interrupter.js
> +      this.logger.warn('[guardian] request should interrupted');
这个是不是用 ctx logger 比较好

2018-12-14 10:15 UTC, popomore commented on app/guardian/interrupter/redirect_interrupter.js
> +      ctx.redirect(this.redirectUrl);
判断下是否存在？

2018-12-14 10:15 UTC, popomore commented on app/guardian/validator/worker_qps_validator.js
> +  return class WorkerQpsValidator extends app.GuardianValidator {
https://github.com/node-modules/qps 这个能用吗

2018-12-14 10:15 UTC, popomore commented on lib/core/guardian.js
> +  guardianMw() {
guardianMiddleware 吧

2018-12-14 10:15 UTC, popomore commented
其他没啥问题

2018-12-22 07:51 UTC, popomore approved these changes

2018-12-22 07:52 UTC, merged